### ISSUE TITLE
Additional issues

### ISSUE THREAD

**Issue by acabal** [mmastrac/h-beam-piper_four-day-planet#7]
- Ending punctuation like periods (but not commas) should go within `<i>` when `<i>` is used for internal thoughts

- Temperatures have a hair space between the number and letter, and no period. See https://standardebooks.org/manual/1.4.0/single-page#8.13.3

- `<em>All hands on deck</em>!` should have the exclamation mark inside `<em>` since it's a complete clause

- You can remove se-lint-ignore.xml because the incorrect casing will be fixed in the next version of the tools

- Can you make the short description a little more descriptive? One sentence that encapsulates the drive of the plot.

- Long description says it's part of the Federation series. If that's an actual series of novels then you need to add collection metadata: https://standardebooks.org/manual/1.4.0/single-page#9.9.3 or also see a book in a series like Sherlock Holmes

- We can probably remove the first `<p>` in the long description. It just restates what's already obvious in the general metadata listing

**Comment by mmastrac** [comment]
Working through these... checking them off here

- [ ]     Ending punctuation like periods (but not commas) should go within <i> when <i> is used for internal thoughts

- [ ]     Temperatures have a hair space between the number and letter, and no period. See https://standardebooks.org/manual/1.4.0/single-page#8.13.3

- [ ]     <em>All hands on deck</em>! should have the exclamation mark inside <em> since it's a complete clause

- [ ]     You can remove se-lint-ignore.xml because the incorrect casing will be fixed in the next version of the tools

- [ ]     Can you make the short description a little more descriptive? One sentence that encapsulates the drive of the plot.

- [ ]     Long description says it's part of the Federation series. If that's an actual series of novels then you need to add collection metadata: https://standardebooks.org/manual/1.4.0/single-page#9.9.3 or also see a book in a series like Sherlock Holmes

 - [ ]    We can probably remove the first <p> in the long description. It just restates what's already obvious in the general metadata listing

**Comment by mmastrac** [comment]
All items addressed, thank you!

c9d3ed274fcbc5594baffae33fd22fdd82f0b34c has the commit with the ending punctuation moved.
